### ISSUE TITLE
Nová ikona

### ISSUE THREAD

**Issue by MarhyCZ** [tomkuba/plugin.video.sport5#2]
Dobrý den,
multimediální centrum je primárně na sledování obsahu, ale taky jeho procházení by mělo být hezkým zážitkem. Napadlo mě redesignovat ikony všech doplňků z tohoto úžasného repozitáře Kodi CZ&SK najednou, aby měli koherentní design, a moderním, hravým vzhledem i vzbudili chuť méně zkušenějším uživatelům je nainstalovat a prozkoumávat :) Návrhy jsem chtěl poslat na jednotlivé github stránky každého doplňku.

Zvolil jsem čtvercová loga, protože průhledná jsou někdy vidět hezky na tmavém skinu a někdy zase jen na světlém. Pozadí je vždy jedna barva či velice lehký gradient. Obsah ikony je vždy 80% na šířku či výšku podle poměru stran. Oficiální wiki Kodi říká, že doplněk by měl mít ikonu 512x512 pixelů, ale to bylo psané v dobách 1080p a když už teď 4K televizory nejsou úplnou raritou, a tyto ikony mají tak jednoduchou grafiku, že mají velice malou velikost na disku, napadlo mě jít rovnou na 1024x1024px.

### Návrhy

Na mém GitHubu se můžete kouknout na ostatní navrhované ikony ve [složce s 2048px návrhy](https://github.com/MarhyCZ/marhycz.github.io/tree/master/kodi-czsk-icons/navrhy)

Případně pár návrhů v jednom obrázku: 
https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/czsknahled.png
_____________________________________________________________________________________________

### Ikona Sport5
2048px návrh ikony Sport5 je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/navrhy/sport5.png)

1024px verze ikony Sport5 pro Kodi je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/1024/sport5.png).

Řídil jsem se dle jejich stránek a televizního vysílání.

**Comment by tomkuba** [comment]
Sport5 má nový web a plugin nefunguje. Nevím, kdy to opravím. Ikony můžu přidat při přepisu.
Mohl bys udělat i společné ikony i pro "play", "next" a "previous" šipky-odkazy?

**Comment by MarhyCZ** [comment]
Ahoj, určitě, to snad nebude problém :)

**Comment by MarhyCZ** [comment]
Tady jsou v 1024px. Pokud byste chtěl variantu třeba se dvěma šipkami vedle sebe, tlustší... stačí napsat :)
Použil jsem "FontAwesome" který se na tohle hodí a navíc je používaný na stránkách sport5.cz
Nebo jste myslel společné ikony pro celý CZ & SK repozitář? Pak bych více popřemýšlel nad barvami. Případně mohu pro každý doplněk vygenerovat jiné barevné verze.

![next](https://user-images.githubusercontent.com/6696872/30766008-ca478d9e-9ff2-11e7-8581-008caa6ca777.png)
![play](https://user-images.githubusercontent.com/6696872/30766010-ca65bc2e-9ff2-11e7-9295-f57e887fbbac.png)
![previous](https://user-images.githubusercontent.com/6696872/30766009-ca5f5050-9ff2-11e7-8c21-79d3eb59c3ed.png)

**Comment by tomkuba** [comment]
Pridal jsem ikony a zaviram issue. Aktualizovany plugin by mel byt k dispozici behem noci.
Diky za spolupraci.
